package fr.iut2.tc4.projet.torque.map;

import java.util.Date;
import java.math.BigDecimal;

import org.apache.torque.Torque;
import org.apache.torque.TorqueException;
import org.apache.torque.map.MapBuilder;
import org.apache.torque.map.DatabaseMap;
import org.apache.torque.map.TableMap;
import org.apache.torque.map.ColumnMap;
import org.apache.torque.map.InheritanceMap;

/**
 * Reference Table
 *
  *  This class was autogenerated by Torque on:
  *
  * [Tue Dec 14 18:33:31 CET 2010]
  *
  */
public class ReferenceMapBuilder implements MapBuilder
{
    /**
     * The name of this class
     */
    public static final String CLASS_NAME =
        "fr.iut2.tc4.projet.torque.map.ReferenceMapBuilder";

    /**
     * The database map.
     */
    private DatabaseMap dbMap = null;

    /**
     * Tells us if this DatabaseMapBuilder is built so that we
     * don't have to re-build it every time.
     *
     * @return true if this DatabaseMapBuilder is built
     */
    public boolean isBuilt()
    {
        return (dbMap != null);
    }

    /**
     * Gets the databasemap this map builder built.
     *
     * @return the databasemap
     */
    public DatabaseMap getDatabaseMap()
    {
        return this.dbMap;
    }

    /**
     * The doBuild() method builds the DatabaseMap
     *
     * @throws TorqueException
     */
    public synchronized void doBuild() throws TorqueException
    {
        if ( isBuilt() ) {
            return;
        }
        dbMap = Torque.getDatabaseMap("gestion");

        dbMap.addTable("reference");
        TableMap tMap = dbMap.getTable("reference");
        tMap.setJavaName("Reference");
        tMap.setOMClass( fr.iut2.tc4.projet.torque.Reference.class );
        tMap.setPeerClass( fr.iut2.tc4.projet.torque.ReferencePeer.class );
        tMap.setDescription("Reference Table");
        tMap.setPrimaryKeyMethod("none");

        ColumnMap cMap = null;


  // ------------- Column: book_id --------------------
        cMap = new ColumnMap( "book_id", tMap);
        cMap.setType( new Integer(0) );
        cMap.setTorqueType( "INTEGER" );
        cMap.setUsePrimitive(true);
        cMap.setPrimaryKey(true);
        cMap.setNotNull(true);
        cMap.setJavaName( "BookId" );
        cMap.setAutoIncrement(false);
        cMap.setProtected(false);
        cMap.setDescription("Book Id");
        cMap.setInheritance("false");
        cMap.setForeignKey("book", "book_id");
        cMap.setPosition(1);
        tMap.addColumn(cMap);
  // ------------- Column: reader_id --------------------
        cMap = new ColumnMap( "reader_id", tMap);
        cMap.setType( new Integer(0) );
        cMap.setTorqueType( "INTEGER" );
        cMap.setUsePrimitive(true);
        cMap.setPrimaryKey(true);
        cMap.setNotNull(true);
        cMap.setJavaName( "ReaderId" );
        cMap.setAutoIncrement(false);
        cMap.setProtected(false);
        cMap.setDescription("Reader Id");
        cMap.setInheritance("false");
        cMap.setForeignKey("reader", "reader_id");
        cMap.setPosition(2);
        tMap.addColumn(cMap);
  // ------------- Column: test --------------------
        cMap = new ColumnMap( "test", tMap);
        cMap.setType( "" );
        cMap.setTorqueType( "VARCHAR" );
        cMap.setUsePrimitive(true);
        cMap.setPrimaryKey(false);
        cMap.setNotNull(false);
        cMap.setJavaName( "Test" );
        cMap.setAutoIncrement(false);
        cMap.setProtected(false);
        cMap.setDescription("test");
        cMap.setInheritance("false");
        cMap.setSize( 24 );
        cMap.setPosition(3);
        tMap.addColumn(cMap);
        tMap.setUseInheritance(false);
    }
}
