package fr.iut2.tc4.projet.torque;


import org.apache.torque.om.Persistent;

/**
 * Author Table
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Tue Dec 14 18:04:55 CET 2010]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */
public  class Author
    extends fr.iut2.tc4.projet.torque.BaseAuthor
    implements Persistent
{
    /** Serial version */
    private static final long serialVersionUID = 1292346295784L;

}
