package fr.iut2.tc4.projet.torque;


import java.math.BigDecimal;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.List;

import org.apache.commons.lang.ObjectUtils;
import org.apache.torque.TorqueException;
import org.apache.torque.map.TableMap;
import org.apache.torque.om.BaseObject;
import org.apache.torque.om.ComboKey;
import org.apache.torque.om.DateKey;
import org.apache.torque.om.NumberKey;
import org.apache.torque.om.ObjectKey;
import org.apache.torque.om.SimpleKey;
import org.apache.torque.om.StringKey;
import org.apache.torque.om.Persistent;
import org.apache.torque.util.Criteria;
import org.apache.torque.util.Transaction;





/**
 * Table des absences
 *
 * This class was autogenerated by Torque on:
 *
 * [Wed Dec 15 09:23:47 CET 2010]
 *
 * You should not use this class directly.  It should not even be
 * extended all references should be to Absence
 */
public abstract class BaseAbsence extends BaseObject
{
    /** Serial version */
    private static final long serialVersionUID = 1292401427137L;

    /** The Peer class */
    private static final AbsencePeer peer =
        new AbsencePeer();


    /** The value for the absenceId field */
    private int absenceId;

    /** The value for the datedebut field */
    private Date datedebut;

    /** The value for the datefin field */
    private Date datefin;

    /** The value for the motif field */
    private String motif;

    /** The value for the etudiantId field */
    private int etudiantId;


    /**
     * Get the AbsenceId
     *
     * @return int
     */
    public int getAbsenceId()
    {
        return absenceId;
    }


    /**
     * Set the value of AbsenceId
     *
     * @param v new value
     */
    public void setAbsenceId(int v) 
    {

        if (this.absenceId != v)
        {
            this.absenceId = v;
            setModified(true);
        }


    }

    /**
     * Get the Datedebut
     *
     * @return Date
     */
    public Date getDatedebut()
    {
        return datedebut;
    }


    /**
     * Set the value of Datedebut
     *
     * @param v new value
     */
    public void setDatedebut(Date v) 
    {

        if (!ObjectUtils.equals(this.datedebut, v))
        {
            this.datedebut = v;
            setModified(true);
        }


    }

    /**
     * Get the Datefin
     *
     * @return Date
     */
    public Date getDatefin()
    {
        return datefin;
    }


    /**
     * Set the value of Datefin
     *
     * @param v new value
     */
    public void setDatefin(Date v) 
    {

        if (!ObjectUtils.equals(this.datefin, v))
        {
            this.datefin = v;
            setModified(true);
        }


    }

    /**
     * Get the Motif
     *
     * @return String
     */
    public String getMotif()
    {
        return motif;
    }


    /**
     * Set the value of Motif
     *
     * @param v new value
     */
    public void setMotif(String v) 
    {

        if (!ObjectUtils.equals(this.motif, v))
        {
            this.motif = v;
            setModified(true);
        }


    }

    /**
     * Get the EtudiantId
     *
     * @return int
     */
    public int getEtudiantId()
    {
        return etudiantId;
    }


    /**
     * Set the value of EtudiantId
     *
     * @param v new value
     */
    public void setEtudiantId(int v) throws TorqueException
    {

        if (this.etudiantId != v)
        {
            this.etudiantId = v;
            setModified(true);
        }


        if (aEtudiant != null && !(aEtudiant.getEtudiantId() == v))
        {
            aEtudiant = null;
        }

    }

    



    private Etudiant aEtudiant;

    /**
     * Declares an association between this object and a Etudiant object
     *
     * @param v Etudiant
     * @throws TorqueException
     */
    public void setEtudiant(Etudiant v) throws TorqueException
    {
        if (v == null)
        {
            setEtudiantId( 0);
        }
        else
        {
            setEtudiantId(v.getEtudiantId());
        }
        aEtudiant = v;
    }


    /**
     * Returns the associated Etudiant object.
     * If it was not retrieved before, the object is retrieved from
     * the database
     *
     * @return the associated Etudiant object
     * @throws TorqueException
     */
    public Etudiant getEtudiant()
        throws TorqueException
    {
        if (aEtudiant == null && (this.etudiantId != 0))
        {
            aEtudiant = EtudiantPeer.retrieveByPK(SimpleKey.keyFor(this.etudiantId));
        }
        return aEtudiant;
    }

    /**
     * Return the associated Etudiant object
     * If it was not retrieved before, the object is retrieved from
     * the database using the passed connection
     *
     * @param connection the connection used to retrieve the associated object
     *        from the database, if it was not retrieved before
     * @return the associated Etudiant object
     * @throws TorqueException
     */
    public Etudiant getEtudiant(Connection connection)
        throws TorqueException
    {
        if (aEtudiant == null && (this.etudiantId != 0))
        {
            aEtudiant = EtudiantPeer.retrieveByPK(SimpleKey.keyFor(this.etudiantId), connection);
        }
        return aEtudiant;
    }

    /**
     * Provides convenient way to set a relationship based on a
     * ObjectKey, for example
     * <code>bar.setFooKey(foo.getPrimaryKey())</code>
     *
     */
    public void setEtudiantKey(ObjectKey key) throws TorqueException
    {

        setEtudiantId(((NumberKey) key).intValue());
    }
   
        
    private static List fieldNames = null;

    /**
     * Generate a list of field names.
     *
     * @return a list of field names
     */
    public static synchronized List getFieldNames()
    {
        if (fieldNames == null)
        {
            fieldNames = new ArrayList();
            fieldNames.add("AbsenceId");
            fieldNames.add("Datedebut");
            fieldNames.add("Datefin");
            fieldNames.add("Motif");
            fieldNames.add("EtudiantId");
            fieldNames = Collections.unmodifiableList(fieldNames);
        }
        return fieldNames;
    }

    /**
     * Retrieves a field from the object by field (Java) name passed in as a String.
     *
     * @param name field name
     * @return value
     */
    public Object getByName(String name)
    {
        if (name.equals("AbsenceId"))
        {
            return new Integer(getAbsenceId());
        }
        if (name.equals("Datedebut"))
        {
            return getDatedebut();
        }
        if (name.equals("Datefin"))
        {
            return getDatefin();
        }
        if (name.equals("Motif"))
        {
            return getMotif();
        }
        if (name.equals("EtudiantId"))
        {
            return new Integer(getEtudiantId());
        }
        return null;
    }

    /**
     * Set a field in the object by field (Java) name.
     *
     * @param name field name
     * @param value field value
     * @return True if value was set, false if not (invalid name / protected field).
     * @throws IllegalArgumentException if object type of value does not match field object type.
     * @throws TorqueException If a problem occurs with the set[Field] method.
     */
    public boolean setByName(String name, Object value )
        throws TorqueException, IllegalArgumentException
    {
        if (name.equals("AbsenceId"))
        {
            if (value == null || ! (Integer.class.isInstance(value)))
            {
                throw new IllegalArgumentException("setByName: value parameter was null or not an Integer object.");
            }
            setAbsenceId(((Integer) value).intValue());
            return true;
        }
        if (name.equals("Datedebut"))
        {
            // Object fields can be null
            if (value != null && ! Date.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setDatedebut((Date) value);
            return true;
        }
        if (name.equals("Datefin"))
        {
            // Object fields can be null
            if (value != null && ! Date.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setDatefin((Date) value);
            return true;
        }
        if (name.equals("Motif"))
        {
            // Object fields can be null
            if (value != null && ! String.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setMotif((String) value);
            return true;
        }
        if (name.equals("EtudiantId"))
        {
            if (value == null || ! (Integer.class.isInstance(value)))
            {
                throw new IllegalArgumentException("setByName: value parameter was null or not an Integer object.");
            }
            setEtudiantId(((Integer) value).intValue());
            return true;
        }
        return false;
    }

    /**
     * Retrieves a field from the object by name passed in
     * as a String.  The String must be one of the static
     * Strings defined in this Class' Peer.
     *
     * @param name peer name
     * @return value
     */
    public Object getByPeerName(String name)
    {
        if (name.equals(AbsencePeer.ABSENCE_ID))
        {
            return new Integer(getAbsenceId());
        }
        if (name.equals(AbsencePeer.DATEDEBUT))
        {
            return getDatedebut();
        }
        if (name.equals(AbsencePeer.DATEFIN))
        {
            return getDatefin();
        }
        if (name.equals(AbsencePeer.MOTIF))
        {
            return getMotif();
        }
        if (name.equals(AbsencePeer.ETUDIANT_ID))
        {
            return new Integer(getEtudiantId());
        }
        return null;
    }

    /**
     * Set field values by Peer Field Name
     *
     * @param name field name
     * @param value field value
     * @return True if value was set, false if not (invalid name / protected field).
     * @throws IllegalArgumentException if object type of value does not match field object type.
     * @throws TorqueException If a problem occurs with the set[Field] method.
     */
    public boolean setByPeerName(String name, Object value)
        throws TorqueException, IllegalArgumentException
    {
      if (AbsencePeer.ABSENCE_ID.equals(name))
        {
            return setByName("AbsenceId", value);
        }
      if (AbsencePeer.DATEDEBUT.equals(name))
        {
            return setByName("Datedebut", value);
        }
      if (AbsencePeer.DATEFIN.equals(name))
        {
            return setByName("Datefin", value);
        }
      if (AbsencePeer.MOTIF.equals(name))
        {
            return setByName("Motif", value);
        }
      if (AbsencePeer.ETUDIANT_ID.equals(name))
        {
            return setByName("EtudiantId", value);
        }
        return false;
    }

    /**
     * Retrieves a field from the object by Position as specified
     * in the xml schema.  Zero-based.
     *
     * @param pos position in xml schema
     * @return value
     */
    public Object getByPosition(int pos)
    {
        if (pos == 0)
        {
            return new Integer(getAbsenceId());
        }
        if (pos == 1)
        {
            return getDatedebut();
        }
        if (pos == 2)
        {
            return getDatefin();
        }
        if (pos == 3)
        {
            return getMotif();
        }
        if (pos == 4)
        {
            return new Integer(getEtudiantId());
        }
        return null;
    }

    /**
     * Set field values by its position (zero based) in the XML schema.
     *
     * @param position The field position
     * @param value field value
     * @return True if value was set, false if not (invalid position / protected field).
     * @throws IllegalArgumentException if object type of value does not match field object type.
     * @throws TorqueException If a problem occurs with the set[Field] method.
     */
    public boolean setByPosition(int position, Object value)
        throws TorqueException, IllegalArgumentException
    {
    if (position == 0)
        {
            return setByName("AbsenceId", value);
        }
    if (position == 1)
        {
            return setByName("Datedebut", value);
        }
    if (position == 2)
        {
            return setByName("Datefin", value);
        }
    if (position == 3)
        {
            return setByName("Motif", value);
        }
    if (position == 4)
        {
            return setByName("EtudiantId", value);
        }
        return false;
    }
     
    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     *
     * @throws Exception
     */
    public void save() throws Exception
    {
        save(AbsencePeer.DATABASE_NAME);
    }

    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     * Note: this code is here because the method body is
     * auto-generated conditionally and therefore needs to be
     * in this file instead of in the super class, BaseObject.
     *
     * @param dbName
     * @throws TorqueException
     */
    public void save(String dbName) throws TorqueException
    {
        Connection con = null;
        try
        {
            con = Transaction.begin(dbName);
            save(con);
            Transaction.commit(con);
        }
        catch(TorqueException e)
        {
            Transaction.safeRollback(con);
            throw e;
        }
    }

    /** flag to prevent endless save loop, if this object is referenced
        by another object which falls in this transaction. */
    private boolean alreadyInSave = false;
    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.  This method
     * is meant to be used as part of a transaction, otherwise use
     * the save() method and the connection details will be handled
     * internally
     *
     * @param con
     * @throws TorqueException
     */
    public void save(Connection con) throws TorqueException
    {
        if (!alreadyInSave)
        {
            alreadyInSave = true;



            // If this object has been modified, then save it to the database.
            if (isModified())
            {
                if (isNew())
                {
                    AbsencePeer.doInsert((Absence) this, con);
                    setNew(false);
                }
                else
                {
                    AbsencePeer.doUpdate((Absence) this, con);
                }
            }

            alreadyInSave = false;
        }
    }


    /**
     * Set the PrimaryKey using ObjectKey.
     *
     * @param key absenceId ObjectKey
     */
    public void setPrimaryKey(ObjectKey key)
        
    {
        setAbsenceId(((NumberKey) key).intValue());
    }

    /**
     * Set the PrimaryKey using a String.
     *
     * @param key
     */
    public void setPrimaryKey(String key) 
    {
        setAbsenceId(Integer.parseInt(key));
    }


    /**
     * returns an id that differentiates this object from others
     * of its class.
     */
    public ObjectKey getPrimaryKey()
    {
        return SimpleKey.keyFor(getAbsenceId());
    }
 

    /**
     * Makes a copy of this object.
     * It creates a new object filling in the simple attributes.
     * It then fills all the association collections and sets the
     * related objects to isNew=true.
     */
    public Absence copy() throws TorqueException
    {
        return copy(true);
    }

    /**
     * Makes a copy of this object using connection.
     * It creates a new object filling in the simple attributes.
     * It then fills all the association collections and sets the
     * related objects to isNew=true.
     *
     * @param con the database connection to read associated objects.
     */
    public Absence copy(Connection con) throws TorqueException
    {
        return copy(true, con);
    }

    /**
     * Makes a copy of this object.
     * It creates a new object filling in the simple attributes.
     * If the parameter deepcopy is true, it then fills all the
     * association collections and sets the related objects to
     * isNew=true.
     *
     * @param deepcopy whether to copy the associated objects.
     */
    public Absence copy(boolean deepcopy) throws TorqueException
    {
        return copyInto(new Absence(), deepcopy);
    }

    /**
     * Makes a copy of this object using connection.
     * It creates a new object filling in the simple attributes.
     * If the parameter deepcopy is true, it then fills all the
     * association collections and sets the related objects to
     * isNew=true.
     *
     * @param deepcopy whether to copy the associated objects.
     * @param con the database connection to read associated objects.
     */
    public Absence copy(boolean deepcopy, Connection con) throws TorqueException
    {
        return copyInto(new Absence(), deepcopy, con);
    }
  
    /**
     * Fills the copyObj with the contents of this object.
     * The associated objects are also copied and treated as new objects.
     *
     * @param copyObj the object to fill.
     */
    protected Absence copyInto(Absence copyObj) throws TorqueException
    {
        return copyInto(copyObj, true);
    }

  
    /**
     * Fills the copyObj with the contents of this object using connection.
     * The associated objects are also copied and treated as new objects.
     *
     * @param copyObj the object to fill.
     * @param con the database connection to read associated objects.
     */
    protected Absence copyInto(Absence copyObj, Connection con) throws TorqueException
    {
        return copyInto(copyObj, true, con);
    }
  
    /**
     * Fills the copyObj with the contents of this object.
     * If deepcopy is true, The associated objects are also copied
     * and treated as new objects.
     *
     * @param copyObj the object to fill.
     * @param deepcopy whether the associated objects should be copied.
     */
    protected Absence copyInto(Absence copyObj, boolean deepcopy) throws TorqueException
    {
        copyObj.setAbsenceId(absenceId);
        copyObj.setDatedebut(datedebut);
        copyObj.setDatefin(datefin);
        copyObj.setMotif(motif);
        copyObj.setEtudiantId(etudiantId);

        copyObj.setAbsenceId( 0);

        if (deepcopy)
        {
        }
        return copyObj;
    }
        
    
    /**
     * Fills the copyObj with the contents of this object using connection.
     * If deepcopy is true, The associated objects are also copied
     * and treated as new objects.
     *
     * @param copyObj the object to fill.
     * @param deepcopy whether the associated objects should be copied.
     * @param con the database connection to read associated objects.
     */
    protected Absence copyInto(Absence copyObj, boolean deepcopy, Connection con) throws TorqueException
    {
        copyObj.setAbsenceId(absenceId);
        copyObj.setDatedebut(datedebut);
        copyObj.setDatefin(datefin);
        copyObj.setMotif(motif);
        copyObj.setEtudiantId(etudiantId);

        copyObj.setAbsenceId( 0);

        if (deepcopy)
        {
        }
        return copyObj;
    }
    
    

    /**
     * returns a peer instance associated with this om.  Since Peer classes
     * are not to have any instance attributes, this method returns the
     * same instance for all member of this class. The method could therefore
     * be static, but this would prevent one from overriding the behavior.
     */
    public AbsencePeer getPeer()
    {
        return peer;
    }

    /**
     * Retrieves the TableMap object related to this Table data without
     * compiler warnings of using getPeer().getTableMap().
     *
     * @return The associated TableMap object.
     */
    public TableMap getTableMap() throws TorqueException
    {
        return AbsencePeer.getTableMap();
    }


    public String toString()
    {
        StringBuffer str = new StringBuffer();
        str.append("Absence:\n");
        str.append("AbsenceId = ")
           .append(getAbsenceId())
           .append("\n");
        str.append("Datedebut = ")
           .append(getDatedebut())
           .append("\n");
        str.append("Datefin = ")
           .append(getDatefin())
           .append("\n");
        str.append("Motif = ")
           .append(getMotif())
           .append("\n");
        str.append("EtudiantId = ")
           .append(getEtudiantId())
           .append("\n");
        return(str.toString());
    }
}
