package fr.iut2.tc4.projet.torque;


import java.math.BigDecimal;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.List;

import org.apache.commons.lang.ObjectUtils;
import org.apache.torque.TorqueException;
import org.apache.torque.map.TableMap;
import org.apache.torque.om.BaseObject;
import org.apache.torque.om.ComboKey;
import org.apache.torque.om.DateKey;
import org.apache.torque.om.NumberKey;
import org.apache.torque.om.ObjectKey;
import org.apache.torque.om.SimpleKey;
import org.apache.torque.om.StringKey;
import org.apache.torque.om.Persistent;
import org.apache.torque.util.Criteria;
import org.apache.torque.util.Transaction;





/**
 * Table des etudiant
 *
 * This class was autogenerated by Torque on:
 *
 * [Wed Dec 15 15:22:40 CET 2010]
 *
 * You should not use this class directly.  It should not even be
 * extended all references should be to Etudiant
 */
public abstract class BaseEtudiant extends BaseObject
{
    /** Serial version */
    private static final long serialVersionUID = 1292422960054L;

    /** The Peer class */
    private static final EtudiantPeer peer =
        new EtudiantPeer();


    /** The value for the etudiantId field */
    private int etudiantId;

    /** The value for the nom field */
    private String nom;

    /** The value for the prenom field */
    private String prenom;


    /**
     * Get the EtudiantId
     *
     * @return int
     */
    public int getEtudiantId()
    {
        return etudiantId;
    }


    /**
     * Set the value of EtudiantId
     *
     * @param v new value
     */
    public void setEtudiantId(int v) throws TorqueException
    {

        if (this.etudiantId != v)
        {
            this.etudiantId = v;
            setModified(true);
        }



        // update associated Absence
        if (collAbsences != null)
        {
            for (int i = 0; i < collAbsences.size(); i++)
            {
                ((Absence) collAbsences.get(i))
                        .setEtudiantId(v);
            }
        }

        // update associated Classe
        if (collClasses != null)
        {
            for (int i = 0; i < collClasses.size(); i++)
            {
                ((Classe) collClasses.get(i))
                        .setEtudiantId(v);
            }
        }

        // update associated Controle
        if (collControles != null)
        {
            for (int i = 0; i < collControles.size(); i++)
            {
                ((Controle) collControles.get(i))
                        .setEtudiantId(v);
            }
        }
    }

    /**
     * Get the Nom
     *
     * @return String
     */
    public String getNom()
    {
        return nom;
    }


    /**
     * Set the value of Nom
     *
     * @param v new value
     */
    public void setNom(String v) 
    {

        if (!ObjectUtils.equals(this.nom, v))
        {
            this.nom = v;
            setModified(true);
        }


    }

    /**
     * Get the Prenom
     *
     * @return String
     */
    public String getPrenom()
    {
        return prenom;
    }


    /**
     * Set the value of Prenom
     *
     * @param v new value
     */
    public void setPrenom(String v) 
    {

        if (!ObjectUtils.equals(this.prenom, v))
        {
            this.prenom = v;
            setModified(true);
        }


    }

       


    /**
     * Collection to store aggregation of collAbsences
     */
    protected List collAbsences;

    /**
     * Temporary storage of collAbsences to save a possible db hit in
     * the event objects are add to the collection, but the
     * complete collection is never requested.
     */
    protected void initAbsences()
    {
        if (collAbsences == null)
        {
            collAbsences = new ArrayList();
        }
    }


    /**
     * Method called to associate a Absence object to this object
     * through the Absence foreign key attribute
     *
     * @param l Absence
     * @throws TorqueException
     */
    public void addAbsence(Absence l) throws TorqueException
    {
        getAbsences().add(l);
        l.setEtudiant((Etudiant) this);
    }

    /**
     * Method called to associate a Absence object to this object
     * through the Absence foreign key attribute using connection.
     *
     * @param l Absence
     * @throws TorqueException
     */
    public void addAbsence(Absence l, Connection con) throws TorqueException
    {
        getAbsences(con).add(l);
        l.setEtudiant((Etudiant) this);
    }

    /**
     * The criteria used to select the current contents of collAbsences
     */
    private Criteria lastAbsencesCriteria = null;

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getAbsences(new Criteria())
     *
     * @return the collection of associated objects
     * @throws TorqueException
     */
    public List getAbsences()
        throws TorqueException
    {
        if (collAbsences == null)
        {
            collAbsences = getAbsences(new Criteria(10));
        }
        return collAbsences;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Etudiant has previously
     * been saved, it will retrieve related Absences from storage.
     * If this Etudiant is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     *
     * @throws TorqueException
     */
    public List getAbsences(Criteria criteria) throws TorqueException
    {
        if (collAbsences == null)
        {
            if (isNew())
            {
               collAbsences = new ArrayList();
            }
            else
            {
                criteria.add(AbsencePeer.ETUDIANT_ID, getEtudiantId() );
                collAbsences = AbsencePeer.doSelect(criteria);
            }
        }
        else
        {
            // criteria has no effect for a new object
            if (!isNew())
            {
                // the following code is to determine if a new query is
                // called for.  If the criteria is the same as the last
                // one, just return the collection.
                criteria.add(AbsencePeer.ETUDIANT_ID, getEtudiantId());
                if (!lastAbsencesCriteria.equals(criteria))
                {
                    collAbsences = AbsencePeer.doSelect(criteria);
                }
            }
        }
        lastAbsencesCriteria = criteria;

        return collAbsences;
    }

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getAbsences(new Criteria(),Connection)
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List getAbsences(Connection con) throws TorqueException
    {
        if (collAbsences == null)
        {
            collAbsences = getAbsences(new Criteria(10), con);
        }
        return collAbsences;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Etudiant has previously
     * been saved, it will retrieve related Absences from storage.
     * If this Etudiant is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List getAbsences(Criteria criteria, Connection con)
            throws TorqueException
    {
        if (collAbsences == null)
        {
            if (isNew())
            {
               collAbsences = new ArrayList();
            }
            else
            {
                 criteria.add(AbsencePeer.ETUDIANT_ID, getEtudiantId());
                 collAbsences = AbsencePeer.doSelect(criteria, con);
             }
         }
         else
         {
             // criteria has no effect for a new object
             if (!isNew())
             {
                 // the following code is to determine if a new query is
                 // called for.  If the criteria is the same as the last
                 // one, just return the collection.
                 criteria.add(AbsencePeer.ETUDIANT_ID, getEtudiantId());
                 if (!lastAbsencesCriteria.equals(criteria))
                 {
                     collAbsences = AbsencePeer.doSelect(criteria, con);
                 }
             }
         }
         lastAbsencesCriteria = criteria;

         return collAbsences;
     }











    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Etudiant is new, it will return
     * an empty collection; or if this Etudiant has previously
     * been saved, it will retrieve related Absences from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in Etudiant.
     */
    protected List getAbsencesJoinEtudiant(Criteria criteria)
        throws TorqueException
    {
        if (collAbsences == null)
        {
            if (isNew())
            {
               collAbsences = new ArrayList();
            }
            else
            {
                criteria.add(AbsencePeer.ETUDIANT_ID, getEtudiantId());
                collAbsences = AbsencePeer.doSelectJoinEtudiant(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            criteria.add(AbsencePeer.ETUDIANT_ID, getEtudiantId());
            if (!lastAbsencesCriteria.equals(criteria))
            {
                collAbsences = AbsencePeer.doSelectJoinEtudiant(criteria);
            }
        }
        lastAbsencesCriteria = criteria;

        return collAbsences;
    }





    /**
     * Collection to store aggregation of collClasses
     */
    protected List collClasses;

    /**
     * Temporary storage of collClasses to save a possible db hit in
     * the event objects are add to the collection, but the
     * complete collection is never requested.
     */
    protected void initClasses()
    {
        if (collClasses == null)
        {
            collClasses = new ArrayList();
        }
    }


    /**
     * Method called to associate a Classe object to this object
     * through the Classe foreign key attribute
     *
     * @param l Classe
     * @throws TorqueException
     */
    public void addClasse(Classe l) throws TorqueException
    {
        getClasses().add(l);
        l.setEtudiant((Etudiant) this);
    }

    /**
     * Method called to associate a Classe object to this object
     * through the Classe foreign key attribute using connection.
     *
     * @param l Classe
     * @throws TorqueException
     */
    public void addClasse(Classe l, Connection con) throws TorqueException
    {
        getClasses(con).add(l);
        l.setEtudiant((Etudiant) this);
    }

    /**
     * The criteria used to select the current contents of collClasses
     */
    private Criteria lastClassesCriteria = null;

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getClasses(new Criteria())
     *
     * @return the collection of associated objects
     * @throws TorqueException
     */
    public List getClasses()
        throws TorqueException
    {
        if (collClasses == null)
        {
            collClasses = getClasses(new Criteria(10));
        }
        return collClasses;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Etudiant has previously
     * been saved, it will retrieve related Classes from storage.
     * If this Etudiant is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     *
     * @throws TorqueException
     */
    public List getClasses(Criteria criteria) throws TorqueException
    {
        if (collClasses == null)
        {
            if (isNew())
            {
               collClasses = new ArrayList();
            }
            else
            {
                criteria.add(ClassePeer.ETUDIANT_ID, getEtudiantId() );
                collClasses = ClassePeer.doSelect(criteria);
            }
        }
        else
        {
            // criteria has no effect for a new object
            if (!isNew())
            {
                // the following code is to determine if a new query is
                // called for.  If the criteria is the same as the last
                // one, just return the collection.
                criteria.add(ClassePeer.ETUDIANT_ID, getEtudiantId());
                if (!lastClassesCriteria.equals(criteria))
                {
                    collClasses = ClassePeer.doSelect(criteria);
                }
            }
        }
        lastClassesCriteria = criteria;

        return collClasses;
    }

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getClasses(new Criteria(),Connection)
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List getClasses(Connection con) throws TorqueException
    {
        if (collClasses == null)
        {
            collClasses = getClasses(new Criteria(10), con);
        }
        return collClasses;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Etudiant has previously
     * been saved, it will retrieve related Classes from storage.
     * If this Etudiant is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List getClasses(Criteria criteria, Connection con)
            throws TorqueException
    {
        if (collClasses == null)
        {
            if (isNew())
            {
               collClasses = new ArrayList();
            }
            else
            {
                 criteria.add(ClassePeer.ETUDIANT_ID, getEtudiantId());
                 collClasses = ClassePeer.doSelect(criteria, con);
             }
         }
         else
         {
             // criteria has no effect for a new object
             if (!isNew())
             {
                 // the following code is to determine if a new query is
                 // called for.  If the criteria is the same as the last
                 // one, just return the collection.
                 criteria.add(ClassePeer.ETUDIANT_ID, getEtudiantId());
                 if (!lastClassesCriteria.equals(criteria))
                 {
                     collClasses = ClassePeer.doSelect(criteria, con);
                 }
             }
         }
         lastClassesCriteria = criteria;

         return collClasses;
     }











    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Etudiant is new, it will return
     * an empty collection; or if this Etudiant has previously
     * been saved, it will retrieve related Classes from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in Etudiant.
     */
    protected List getClassesJoinEtudiant(Criteria criteria)
        throws TorqueException
    {
        if (collClasses == null)
        {
            if (isNew())
            {
               collClasses = new ArrayList();
            }
            else
            {
                criteria.add(ClassePeer.ETUDIANT_ID, getEtudiantId());
                collClasses = ClassePeer.doSelectJoinEtudiant(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            criteria.add(ClassePeer.ETUDIANT_ID, getEtudiantId());
            if (!lastClassesCriteria.equals(criteria))
            {
                collClasses = ClassePeer.doSelectJoinEtudiant(criteria);
            }
        }
        lastClassesCriteria = criteria;

        return collClasses;
    }









    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Etudiant is new, it will return
     * an empty collection; or if this Etudiant has previously
     * been saved, it will retrieve related Classes from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in Etudiant.
     */
    protected List getClassesJoinMatiere(Criteria criteria)
        throws TorqueException
    {
        if (collClasses == null)
        {
            if (isNew())
            {
               collClasses = new ArrayList();
            }
            else
            {
                criteria.add(ClassePeer.ETUDIANT_ID, getEtudiantId());
                collClasses = ClassePeer.doSelectJoinMatiere(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            criteria.add(ClassePeer.ETUDIANT_ID, getEtudiantId());
            if (!lastClassesCriteria.equals(criteria))
            {
                collClasses = ClassePeer.doSelectJoinMatiere(criteria);
            }
        }
        lastClassesCriteria = criteria;

        return collClasses;
    }





    /**
     * Collection to store aggregation of collControles
     */
    protected List collControles;

    /**
     * Temporary storage of collControles to save a possible db hit in
     * the event objects are add to the collection, but the
     * complete collection is never requested.
     */
    protected void initControles()
    {
        if (collControles == null)
        {
            collControles = new ArrayList();
        }
    }


    /**
     * Method called to associate a Controle object to this object
     * through the Controle foreign key attribute
     *
     * @param l Controle
     * @throws TorqueException
     */
    public void addControle(Controle l) throws TorqueException
    {
        getControles().add(l);
        l.setEtudiant((Etudiant) this);
    }

    /**
     * Method called to associate a Controle object to this object
     * through the Controle foreign key attribute using connection.
     *
     * @param l Controle
     * @throws TorqueException
     */
    public void addControle(Controle l, Connection con) throws TorqueException
    {
        getControles(con).add(l);
        l.setEtudiant((Etudiant) this);
    }

    /**
     * The criteria used to select the current contents of collControles
     */
    private Criteria lastControlesCriteria = null;

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getControles(new Criteria())
     *
     * @return the collection of associated objects
     * @throws TorqueException
     */
    public List getControles()
        throws TorqueException
    {
        if (collControles == null)
        {
            collControles = getControles(new Criteria(10));
        }
        return collControles;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Etudiant has previously
     * been saved, it will retrieve related Controles from storage.
     * If this Etudiant is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     *
     * @throws TorqueException
     */
    public List getControles(Criteria criteria) throws TorqueException
    {
        if (collControles == null)
        {
            if (isNew())
            {
               collControles = new ArrayList();
            }
            else
            {
                criteria.add(ControlePeer.ETUDIANT_ID, getEtudiantId() );
                collControles = ControlePeer.doSelect(criteria);
            }
        }
        else
        {
            // criteria has no effect for a new object
            if (!isNew())
            {
                // the following code is to determine if a new query is
                // called for.  If the criteria is the same as the last
                // one, just return the collection.
                criteria.add(ControlePeer.ETUDIANT_ID, getEtudiantId());
                if (!lastControlesCriteria.equals(criteria))
                {
                    collControles = ControlePeer.doSelect(criteria);
                }
            }
        }
        lastControlesCriteria = criteria;

        return collControles;
    }

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getControles(new Criteria(),Connection)
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List getControles(Connection con) throws TorqueException
    {
        if (collControles == null)
        {
            collControles = getControles(new Criteria(10), con);
        }
        return collControles;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Etudiant has previously
     * been saved, it will retrieve related Controles from storage.
     * If this Etudiant is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List getControles(Criteria criteria, Connection con)
            throws TorqueException
    {
        if (collControles == null)
        {
            if (isNew())
            {
               collControles = new ArrayList();
            }
            else
            {
                 criteria.add(ControlePeer.ETUDIANT_ID, getEtudiantId());
                 collControles = ControlePeer.doSelect(criteria, con);
             }
         }
         else
         {
             // criteria has no effect for a new object
             if (!isNew())
             {
                 // the following code is to determine if a new query is
                 // called for.  If the criteria is the same as the last
                 // one, just return the collection.
                 criteria.add(ControlePeer.ETUDIANT_ID, getEtudiantId());
                 if (!lastControlesCriteria.equals(criteria))
                 {
                     collControles = ControlePeer.doSelect(criteria, con);
                 }
             }
         }
         lastControlesCriteria = criteria;

         return collControles;
     }











    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Etudiant is new, it will return
     * an empty collection; or if this Etudiant has previously
     * been saved, it will retrieve related Controles from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in Etudiant.
     */
    protected List getControlesJoinEtudiant(Criteria criteria)
        throws TorqueException
    {
        if (collControles == null)
        {
            if (isNew())
            {
               collControles = new ArrayList();
            }
            else
            {
                criteria.add(ControlePeer.ETUDIANT_ID, getEtudiantId());
                collControles = ControlePeer.doSelectJoinEtudiant(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            criteria.add(ControlePeer.ETUDIANT_ID, getEtudiantId());
            if (!lastControlesCriteria.equals(criteria))
            {
                collControles = ControlePeer.doSelectJoinEtudiant(criteria);
            }
        }
        lastControlesCriteria = criteria;

        return collControles;
    }









    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Etudiant is new, it will return
     * an empty collection; or if this Etudiant has previously
     * been saved, it will retrieve related Controles from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in Etudiant.
     */
    protected List getControlesJoinMatiere(Criteria criteria)
        throws TorqueException
    {
        if (collControles == null)
        {
            if (isNew())
            {
               collControles = new ArrayList();
            }
            else
            {
                criteria.add(ControlePeer.ETUDIANT_ID, getEtudiantId());
                collControles = ControlePeer.doSelectJoinMatiere(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            criteria.add(ControlePeer.ETUDIANT_ID, getEtudiantId());
            if (!lastControlesCriteria.equals(criteria))
            {
                collControles = ControlePeer.doSelectJoinMatiere(criteria);
            }
        }
        lastControlesCriteria = criteria;

        return collControles;
    }



        
    private static List fieldNames = null;

    /**
     * Generate a list of field names.
     *
     * @return a list of field names
     */
    public static synchronized List getFieldNames()
    {
        if (fieldNames == null)
        {
            fieldNames = new ArrayList();
            fieldNames.add("EtudiantId");
            fieldNames.add("Nom");
            fieldNames.add("Prenom");
            fieldNames = Collections.unmodifiableList(fieldNames);
        }
        return fieldNames;
    }

    /**
     * Retrieves a field from the object by field (Java) name passed in as a String.
     *
     * @param name field name
     * @return value
     */
    public Object getByName(String name)
    {
        if (name.equals("EtudiantId"))
        {
            return new Integer(getEtudiantId());
        }
        if (name.equals("Nom"))
        {
            return getNom();
        }
        if (name.equals("Prenom"))
        {
            return getPrenom();
        }
        return null;
    }

    /**
     * Set a field in the object by field (Java) name.
     *
     * @param name field name
     * @param value field value
     * @return True if value was set, false if not (invalid name / protected field).
     * @throws IllegalArgumentException if object type of value does not match field object type.
     * @throws TorqueException If a problem occurs with the set[Field] method.
     */
    public boolean setByName(String name, Object value )
        throws TorqueException, IllegalArgumentException
    {
        if (name.equals("EtudiantId"))
        {
            if (value == null || ! (Integer.class.isInstance(value)))
            {
                throw new IllegalArgumentException("setByName: value parameter was null or not an Integer object.");
            }
            setEtudiantId(((Integer) value).intValue());
            return true;
        }
        if (name.equals("Nom"))
        {
            // Object fields can be null
            if (value != null && ! String.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setNom((String) value);
            return true;
        }
        if (name.equals("Prenom"))
        {
            // Object fields can be null
            if (value != null && ! String.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setPrenom((String) value);
            return true;
        }
        return false;
    }

    /**
     * Retrieves a field from the object by name passed in
     * as a String.  The String must be one of the static
     * Strings defined in this Class' Peer.
     *
     * @param name peer name
     * @return value
     */
    public Object getByPeerName(String name)
    {
        if (name.equals(EtudiantPeer.ETUDIANT_ID))
        {
            return new Integer(getEtudiantId());
        }
        if (name.equals(EtudiantPeer.NOM))
        {
            return getNom();
        }
        if (name.equals(EtudiantPeer.PRENOM))
        {
            return getPrenom();
        }
        return null;
    }

    /**
     * Set field values by Peer Field Name
     *
     * @param name field name
     * @param value field value
     * @return True if value was set, false if not (invalid name / protected field).
     * @throws IllegalArgumentException if object type of value does not match field object type.
     * @throws TorqueException If a problem occurs with the set[Field] method.
     */
    public boolean setByPeerName(String name, Object value)
        throws TorqueException, IllegalArgumentException
    {
      if (EtudiantPeer.ETUDIANT_ID.equals(name))
        {
            return setByName("EtudiantId", value);
        }
      if (EtudiantPeer.NOM.equals(name))
        {
            return setByName("Nom", value);
        }
      if (EtudiantPeer.PRENOM.equals(name))
        {
            return setByName("Prenom", value);
        }
        return false;
    }

    /**
     * Retrieves a field from the object by Position as specified
     * in the xml schema.  Zero-based.
     *
     * @param pos position in xml schema
     * @return value
     */
    public Object getByPosition(int pos)
    {
        if (pos == 0)
        {
            return new Integer(getEtudiantId());
        }
        if (pos == 1)
        {
            return getNom();
        }
        if (pos == 2)
        {
            return getPrenom();
        }
        return null;
    }

    /**
     * Set field values by its position (zero based) in the XML schema.
     *
     * @param position The field position
     * @param value field value
     * @return True if value was set, false if not (invalid position / protected field).
     * @throws IllegalArgumentException if object type of value does not match field object type.
     * @throws TorqueException If a problem occurs with the set[Field] method.
     */
    public boolean setByPosition(int position, Object value)
        throws TorqueException, IllegalArgumentException
    {
    if (position == 0)
        {
            return setByName("EtudiantId", value);
        }
    if (position == 1)
        {
            return setByName("Nom", value);
        }
    if (position == 2)
        {
            return setByName("Prenom", value);
        }
        return false;
    }
     
    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     *
     * @throws Exception
     */
    public void save() throws Exception
    {
        save(EtudiantPeer.DATABASE_NAME);
    }

    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     * Note: this code is here because the method body is
     * auto-generated conditionally and therefore needs to be
     * in this file instead of in the super class, BaseObject.
     *
     * @param dbName
     * @throws TorqueException
     */
    public void save(String dbName) throws TorqueException
    {
        Connection con = null;
        try
        {
            con = Transaction.begin(dbName);
            save(con);
            Transaction.commit(con);
        }
        catch(TorqueException e)
        {
            Transaction.safeRollback(con);
            throw e;
        }
    }

    /** flag to prevent endless save loop, if this object is referenced
        by another object which falls in this transaction. */
    private boolean alreadyInSave = false;
    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.  This method
     * is meant to be used as part of a transaction, otherwise use
     * the save() method and the connection details will be handled
     * internally
     *
     * @param con
     * @throws TorqueException
     */
    public void save(Connection con) throws TorqueException
    {
        if (!alreadyInSave)
        {
            alreadyInSave = true;



            // If this object has been modified, then save it to the database.
            if (isModified())
            {
                if (isNew())
                {
                    EtudiantPeer.doInsert((Etudiant) this, con);
                    setNew(false);
                }
                else
                {
                    EtudiantPeer.doUpdate((Etudiant) this, con);
                }
            }


            if (collAbsences != null)
            {
                for (int i = 0; i < collAbsences.size(); i++)
                {
                    ((Absence) collAbsences.get(i)).save(con);
                }
            }

            if (collClasses != null)
            {
                for (int i = 0; i < collClasses.size(); i++)
                {
                    ((Classe) collClasses.get(i)).save(con);
                }
            }

            if (collControles != null)
            {
                for (int i = 0; i < collControles.size(); i++)
                {
                    ((Controle) collControles.get(i)).save(con);
                }
            }
            alreadyInSave = false;
        }
    }


    /**
     * Set the PrimaryKey using ObjectKey.
     *
     * @param key etudiantId ObjectKey
     */
    public void setPrimaryKey(ObjectKey key)
        throws TorqueException
    {
        setEtudiantId(((NumberKey) key).intValue());
    }

    /**
     * Set the PrimaryKey using a String.
     *
     * @param key
     */
    public void setPrimaryKey(String key) throws TorqueException
    {
        setEtudiantId(Integer.parseInt(key));
    }


    /**
     * returns an id that differentiates this object from others
     * of its class.
     */
    public ObjectKey getPrimaryKey()
    {
        return SimpleKey.keyFor(getEtudiantId());
    }
 

    /**
     * Makes a copy of this object.
     * It creates a new object filling in the simple attributes.
     * It then fills all the association collections and sets the
     * related objects to isNew=true.
     */
    public Etudiant copy() throws TorqueException
    {
        return copy(true);
    }

    /**
     * Makes a copy of this object using connection.
     * It creates a new object filling in the simple attributes.
     * It then fills all the association collections and sets the
     * related objects to isNew=true.
     *
     * @param con the database connection to read associated objects.
     */
    public Etudiant copy(Connection con) throws TorqueException
    {
        return copy(true, con);
    }

    /**
     * Makes a copy of this object.
     * It creates a new object filling in the simple attributes.
     * If the parameter deepcopy is true, it then fills all the
     * association collections and sets the related objects to
     * isNew=true.
     *
     * @param deepcopy whether to copy the associated objects.
     */
    public Etudiant copy(boolean deepcopy) throws TorqueException
    {
        return copyInto(new Etudiant(), deepcopy);
    }

    /**
     * Makes a copy of this object using connection.
     * It creates a new object filling in the simple attributes.
     * If the parameter deepcopy is true, it then fills all the
     * association collections and sets the related objects to
     * isNew=true.
     *
     * @param deepcopy whether to copy the associated objects.
     * @param con the database connection to read associated objects.
     */
    public Etudiant copy(boolean deepcopy, Connection con) throws TorqueException
    {
        return copyInto(new Etudiant(), deepcopy, con);
    }
  
    /**
     * Fills the copyObj with the contents of this object.
     * The associated objects are also copied and treated as new objects.
     *
     * @param copyObj the object to fill.
     */
    protected Etudiant copyInto(Etudiant copyObj) throws TorqueException
    {
        return copyInto(copyObj, true);
    }

  
    /**
     * Fills the copyObj with the contents of this object using connection.
     * The associated objects are also copied and treated as new objects.
     *
     * @param copyObj the object to fill.
     * @param con the database connection to read associated objects.
     */
    protected Etudiant copyInto(Etudiant copyObj, Connection con) throws TorqueException
    {
        return copyInto(copyObj, true, con);
    }
  
    /**
     * Fills the copyObj with the contents of this object.
     * If deepcopy is true, The associated objects are also copied
     * and treated as new objects.
     *
     * @param copyObj the object to fill.
     * @param deepcopy whether the associated objects should be copied.
     */
    protected Etudiant copyInto(Etudiant copyObj, boolean deepcopy) throws TorqueException
    {
        copyObj.setEtudiantId(etudiantId);
        copyObj.setNom(nom);
        copyObj.setPrenom(prenom);

        copyObj.setEtudiantId( 0);

        if (deepcopy)
        {


        List vAbsences = getAbsences();
        if (vAbsences != null)
        {
            for (int i = 0; i < vAbsences.size(); i++)
            {
                Absence obj = (Absence) vAbsences.get(i);
                copyObj.addAbsence(obj.copy());
            }
        }
        else
        {
            copyObj.collAbsences = null;
        }


        List vClasses = getClasses();
        if (vClasses != null)
        {
            for (int i = 0; i < vClasses.size(); i++)
            {
                Classe obj = (Classe) vClasses.get(i);
                copyObj.addClasse(obj.copy());
            }
        }
        else
        {
            copyObj.collClasses = null;
        }


        List vControles = getControles();
        if (vControles != null)
        {
            for (int i = 0; i < vControles.size(); i++)
            {
                Controle obj = (Controle) vControles.get(i);
                copyObj.addControle(obj.copy());
            }
        }
        else
        {
            copyObj.collControles = null;
        }
        }
        return copyObj;
    }
        
    
    /**
     * Fills the copyObj with the contents of this object using connection.
     * If deepcopy is true, The associated objects are also copied
     * and treated as new objects.
     *
     * @param copyObj the object to fill.
     * @param deepcopy whether the associated objects should be copied.
     * @param con the database connection to read associated objects.
     */
    protected Etudiant copyInto(Etudiant copyObj, boolean deepcopy, Connection con) throws TorqueException
    {
        copyObj.setEtudiantId(etudiantId);
        copyObj.setNom(nom);
        copyObj.setPrenom(prenom);

        copyObj.setEtudiantId( 0);

        if (deepcopy)
        {


        List vAbsences = getAbsences(con);
        if (vAbsences != null)
        {
            for (int i = 0; i < vAbsences.size(); i++)
            {
                Absence obj = (Absence) vAbsences.get(i);
                copyObj.addAbsence(obj.copy(con), con);
            }
        }
        else
        {
            copyObj.collAbsences = null;
        }


        List vClasses = getClasses(con);
        if (vClasses != null)
        {
            for (int i = 0; i < vClasses.size(); i++)
            {
                Classe obj = (Classe) vClasses.get(i);
                copyObj.addClasse(obj.copy(con), con);
            }
        }
        else
        {
            copyObj.collClasses = null;
        }


        List vControles = getControles(con);
        if (vControles != null)
        {
            for (int i = 0; i < vControles.size(); i++)
            {
                Controle obj = (Controle) vControles.get(i);
                copyObj.addControle(obj.copy(con), con);
            }
        }
        else
        {
            copyObj.collControles = null;
        }
        }
        return copyObj;
    }
    
    

    /**
     * returns a peer instance associated with this om.  Since Peer classes
     * are not to have any instance attributes, this method returns the
     * same instance for all member of this class. The method could therefore
     * be static, but this would prevent one from overriding the behavior.
     */
    public EtudiantPeer getPeer()
    {
        return peer;
    }

    /**
     * Retrieves the TableMap object related to this Table data without
     * compiler warnings of using getPeer().getTableMap().
     *
     * @return The associated TableMap object.
     */
    public TableMap getTableMap() throws TorqueException
    {
        return EtudiantPeer.getTableMap();
    }


    public String toString()
    {
        StringBuffer str = new StringBuffer();
        str.append("Etudiant:\n");
        str.append("EtudiantId = ")
           .append(getEtudiantId())
           .append("\n");
        str.append("Nom = ")
           .append(getNom())
           .append("\n");
        str.append("Prenom = ")
           .append(getPrenom())
           .append("\n");
        return(str.toString());
    }
}
