package fr.iut2.tc4.projet.torque;


import java.math.BigDecimal;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.List;

import org.apache.commons.lang.ObjectUtils;
import org.apache.torque.TorqueException;
import org.apache.torque.map.TableMap;
import org.apache.torque.om.BaseObject;
import org.apache.torque.om.ComboKey;
import org.apache.torque.om.DateKey;
import org.apache.torque.om.NumberKey;
import org.apache.torque.om.ObjectKey;
import org.apache.torque.om.SimpleKey;
import org.apache.torque.om.StringKey;
import org.apache.torque.om.Persistent;
import org.apache.torque.util.Criteria;
import org.apache.torque.util.Transaction;





/**
 * Reference Table
 *
 * This class was autogenerated by Torque on:
 *
 * [Tue Dec 14 18:33:31 CET 2010]
 *
 * You should not use this class directly.  It should not even be
 * extended all references should be to Reference
 */
public abstract class BaseReference extends BaseObject
{
    /** Serial version */
    private static final long serialVersionUID = 1292348011746L;

    /** The Peer class */
    private static final ReferencePeer peer =
        new ReferencePeer();


    /** The value for the bookId field */
    private int bookId;

    /** The value for the readerId field */
    private int readerId;

    /** The value for the test field */
    private String test;


    /**
     * Get the BookId
     *
     * @return int
     */
    public int getBookId()
    {
        return bookId;
    }


    /**
     * Set the value of BookId
     *
     * @param v new value
     */
    public void setBookId(int v) throws TorqueException
    {

        if (this.bookId != v)
        {
            this.bookId = v;
            setModified(true);
        }


        if (aBook != null && !(aBook.getBookId() == v))
        {
            aBook = null;
        }

    }

    /**
     * Get the ReaderId
     *
     * @return int
     */
    public int getReaderId()
    {
        return readerId;
    }


    /**
     * Set the value of ReaderId
     *
     * @param v new value
     */
    public void setReaderId(int v) throws TorqueException
    {

        if (this.readerId != v)
        {
            this.readerId = v;
            setModified(true);
        }


        if (aReader != null && !(aReader.getReaderId() == v))
        {
            aReader = null;
        }

    }

    /**
     * Get the Test
     *
     * @return String
     */
    public String getTest()
    {
        return test;
    }


    /**
     * Set the value of Test
     *
     * @param v new value
     */
    public void setTest(String v) 
    {

        if (!ObjectUtils.equals(this.test, v))
        {
            this.test = v;
            setModified(true);
        }


    }

    



    private Book aBook;

    /**
     * Declares an association between this object and a Book object
     *
     * @param v Book
     * @throws TorqueException
     */
    public void setBook(Book v) throws TorqueException
    {
        if (v == null)
        {
            setBookId( 0);
        }
        else
        {
            setBookId(v.getBookId());
        }
        aBook = v;
    }


    /**
     * Returns the associated Book object.
     * If it was not retrieved before, the object is retrieved from
     * the database
     *
     * @return the associated Book object
     * @throws TorqueException
     */
    public Book getBook()
        throws TorqueException
    {
        if (aBook == null && (this.bookId != 0))
        {
            aBook = BookPeer.retrieveByPK(SimpleKey.keyFor(this.bookId));
        }
        return aBook;
    }

    /**
     * Return the associated Book object
     * If it was not retrieved before, the object is retrieved from
     * the database using the passed connection
     *
     * @param connection the connection used to retrieve the associated object
     *        from the database, if it was not retrieved before
     * @return the associated Book object
     * @throws TorqueException
     */
    public Book getBook(Connection connection)
        throws TorqueException
    {
        if (aBook == null && (this.bookId != 0))
        {
            aBook = BookPeer.retrieveByPK(SimpleKey.keyFor(this.bookId), connection);
        }
        return aBook;
    }

    /**
     * Provides convenient way to set a relationship based on a
     * ObjectKey, for example
     * <code>bar.setFooKey(foo.getPrimaryKey())</code>
     *
     */
    public void setBookKey(ObjectKey key) throws TorqueException
    {

        setBookId(((NumberKey) key).intValue());
    }




    private Reader aReader;

    /**
     * Declares an association between this object and a Reader object
     *
     * @param v Reader
     * @throws TorqueException
     */
    public void setReader(Reader v) throws TorqueException
    {
        if (v == null)
        {
            setReaderId( 0);
        }
        else
        {
            setReaderId(v.getReaderId());
        }
        aReader = v;
    }


    /**
     * Returns the associated Reader object.
     * If it was not retrieved before, the object is retrieved from
     * the database
     *
     * @return the associated Reader object
     * @throws TorqueException
     */
    public Reader getReader()
        throws TorqueException
    {
        if (aReader == null && (this.readerId != 0))
        {
            aReader = ReaderPeer.retrieveByPK(SimpleKey.keyFor(this.readerId));
        }
        return aReader;
    }

    /**
     * Return the associated Reader object
     * If it was not retrieved before, the object is retrieved from
     * the database using the passed connection
     *
     * @param connection the connection used to retrieve the associated object
     *        from the database, if it was not retrieved before
     * @return the associated Reader object
     * @throws TorqueException
     */
    public Reader getReader(Connection connection)
        throws TorqueException
    {
        if (aReader == null && (this.readerId != 0))
        {
            aReader = ReaderPeer.retrieveByPK(SimpleKey.keyFor(this.readerId), connection);
        }
        return aReader;
    }

    /**
     * Provides convenient way to set a relationship based on a
     * ObjectKey, for example
     * <code>bar.setFooKey(foo.getPrimaryKey())</code>
     *
     */
    public void setReaderKey(ObjectKey key) throws TorqueException
    {

        setReaderId(((NumberKey) key).intValue());
    }
   
        
    private static List fieldNames = null;

    /**
     * Generate a list of field names.
     *
     * @return a list of field names
     */
    public static synchronized List getFieldNames()
    {
        if (fieldNames == null)
        {
            fieldNames = new ArrayList();
            fieldNames.add("BookId");
            fieldNames.add("ReaderId");
            fieldNames.add("Test");
            fieldNames = Collections.unmodifiableList(fieldNames);
        }
        return fieldNames;
    }

    /**
     * Retrieves a field from the object by field (Java) name passed in as a String.
     *
     * @param name field name
     * @return value
     */
    public Object getByName(String name)
    {
        if (name.equals("BookId"))
        {
            return new Integer(getBookId());
        }
        if (name.equals("ReaderId"))
        {
            return new Integer(getReaderId());
        }
        if (name.equals("Test"))
        {
            return getTest();
        }
        return null;
    }

    /**
     * Set a field in the object by field (Java) name.
     *
     * @param name field name
     * @param value field value
     * @return True if value was set, false if not (invalid name / protected field).
     * @throws IllegalArgumentException if object type of value does not match field object type.
     * @throws TorqueException If a problem occurs with the set[Field] method.
     */
    public boolean setByName(String name, Object value )
        throws TorqueException, IllegalArgumentException
    {
        if (name.equals("BookId"))
        {
            if (value == null || ! (Integer.class.isInstance(value)))
            {
                throw new IllegalArgumentException("setByName: value parameter was null or not an Integer object.");
            }
            setBookId(((Integer) value).intValue());
            return true;
        }
        if (name.equals("ReaderId"))
        {
            if (value == null || ! (Integer.class.isInstance(value)))
            {
                throw new IllegalArgumentException("setByName: value parameter was null or not an Integer object.");
            }
            setReaderId(((Integer) value).intValue());
            return true;
        }
        if (name.equals("Test"))
        {
            // Object fields can be null
            if (value != null && ! String.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setTest((String) value);
            return true;
        }
        return false;
    }

    /**
     * Retrieves a field from the object by name passed in
     * as a String.  The String must be one of the static
     * Strings defined in this Class' Peer.
     *
     * @param name peer name
     * @return value
     */
    public Object getByPeerName(String name)
    {
        if (name.equals(ReferencePeer.BOOK_ID))
        {
            return new Integer(getBookId());
        }
        if (name.equals(ReferencePeer.READER_ID))
        {
            return new Integer(getReaderId());
        }
        if (name.equals(ReferencePeer.TEST))
        {
            return getTest();
        }
        return null;
    }

    /**
     * Set field values by Peer Field Name
     *
     * @param name field name
     * @param value field value
     * @return True if value was set, false if not (invalid name / protected field).
     * @throws IllegalArgumentException if object type of value does not match field object type.
     * @throws TorqueException If a problem occurs with the set[Field] method.
     */
    public boolean setByPeerName(String name, Object value)
        throws TorqueException, IllegalArgumentException
    {
      if (ReferencePeer.BOOK_ID.equals(name))
        {
            return setByName("BookId", value);
        }
      if (ReferencePeer.READER_ID.equals(name))
        {
            return setByName("ReaderId", value);
        }
      if (ReferencePeer.TEST.equals(name))
        {
            return setByName("Test", value);
        }
        return false;
    }

    /**
     * Retrieves a field from the object by Position as specified
     * in the xml schema.  Zero-based.
     *
     * @param pos position in xml schema
     * @return value
     */
    public Object getByPosition(int pos)
    {
        if (pos == 0)
        {
            return new Integer(getBookId());
        }
        if (pos == 1)
        {
            return new Integer(getReaderId());
        }
        if (pos == 2)
        {
            return getTest();
        }
        return null;
    }

    /**
     * Set field values by its position (zero based) in the XML schema.
     *
     * @param position The field position
     * @param value field value
     * @return True if value was set, false if not (invalid position / protected field).
     * @throws IllegalArgumentException if object type of value does not match field object type.
     * @throws TorqueException If a problem occurs with the set[Field] method.
     */
    public boolean setByPosition(int position, Object value)
        throws TorqueException, IllegalArgumentException
    {
    if (position == 0)
        {
            return setByName("BookId", value);
        }
    if (position == 1)
        {
            return setByName("ReaderId", value);
        }
    if (position == 2)
        {
            return setByName("Test", value);
        }
        return false;
    }
     
    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     *
     * @throws Exception
     */
    public void save() throws Exception
    {
        save(ReferencePeer.DATABASE_NAME);
    }

    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     * Note: this code is here because the method body is
     * auto-generated conditionally and therefore needs to be
     * in this file instead of in the super class, BaseObject.
     *
     * @param dbName
     * @throws TorqueException
     */
    public void save(String dbName) throws TorqueException
    {
        Connection con = null;
        try
        {
            con = Transaction.begin(dbName);
            save(con);
            Transaction.commit(con);
        }
        catch(TorqueException e)
        {
            Transaction.safeRollback(con);
            throw e;
        }
    }

    /** flag to prevent endless save loop, if this object is referenced
        by another object which falls in this transaction. */
    private boolean alreadyInSave = false;
    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.  This method
     * is meant to be used as part of a transaction, otherwise use
     * the save() method and the connection details will be handled
     * internally
     *
     * @param con
     * @throws TorqueException
     */
    public void save(Connection con) throws TorqueException
    {
        if (!alreadyInSave)
        {
            alreadyInSave = true;



            // If this object has been modified, then save it to the database.
            if (isModified())
            {
                if (isNew())
                {
                    ReferencePeer.doInsert((Reference) this, con);
                    setNew(false);
                }
                else
                {
                    ReferencePeer.doUpdate((Reference) this, con);
                }
            }

            alreadyInSave = false;
        }
    }



    private final SimpleKey[] pks = new SimpleKey[2];
    private final ComboKey comboPK = new ComboKey(pks);

    /**
     * Set the PrimaryKey with an ObjectKey
     *
     * @param key
     */
    public void setPrimaryKey(ObjectKey key) throws TorqueException
    {
        SimpleKey[] keys = (SimpleKey[]) key.getValue();
        setBookId(((NumberKey)keys[0]).intValue());
        setReaderId(((NumberKey)keys[1]).intValue());
    }

    /**
     * Set the PrimaryKey using SimpleKeys.
     *
     * @param bookId int
     * @param readerId int
     */
    public void setPrimaryKey( int bookId, int readerId)
        throws TorqueException
    {
        setBookId(bookId);
        setReaderId(readerId);
    }

    /**
     * Set the PrimaryKey using a String.
     */
    public void setPrimaryKey(String key) throws TorqueException
    {
        setPrimaryKey(new ComboKey(key));
    }

    /**
     * returns an id that differentiates this object from others
     * of its class.
     */
    public ObjectKey getPrimaryKey()
    {
        pks[0] = SimpleKey.keyFor(getBookId());
        pks[1] = SimpleKey.keyFor(getReaderId());
        return comboPK;
    }
 

    /**
     * Makes a copy of this object.
     * It creates a new object filling in the simple attributes.
     * It then fills all the association collections and sets the
     * related objects to isNew=true.
     */
    public Reference copy() throws TorqueException
    {
        return copy(true);
    }

    /**
     * Makes a copy of this object using connection.
     * It creates a new object filling in the simple attributes.
     * It then fills all the association collections and sets the
     * related objects to isNew=true.
     *
     * @param con the database connection to read associated objects.
     */
    public Reference copy(Connection con) throws TorqueException
    {
        return copy(true, con);
    }

    /**
     * Makes a copy of this object.
     * It creates a new object filling in the simple attributes.
     * If the parameter deepcopy is true, it then fills all the
     * association collections and sets the related objects to
     * isNew=true.
     *
     * @param deepcopy whether to copy the associated objects.
     */
    public Reference copy(boolean deepcopy) throws TorqueException
    {
        return copyInto(new Reference(), deepcopy);
    }

    /**
     * Makes a copy of this object using connection.
     * It creates a new object filling in the simple attributes.
     * If the parameter deepcopy is true, it then fills all the
     * association collections and sets the related objects to
     * isNew=true.
     *
     * @param deepcopy whether to copy the associated objects.
     * @param con the database connection to read associated objects.
     */
    public Reference copy(boolean deepcopy, Connection con) throws TorqueException
    {
        return copyInto(new Reference(), deepcopy, con);
    }
  
    /**
     * Fills the copyObj with the contents of this object.
     * The associated objects are also copied and treated as new objects.
     *
     * @param copyObj the object to fill.
     */
    protected Reference copyInto(Reference copyObj) throws TorqueException
    {
        return copyInto(copyObj, true);
    }

  
    /**
     * Fills the copyObj with the contents of this object using connection.
     * The associated objects are also copied and treated as new objects.
     *
     * @param copyObj the object to fill.
     * @param con the database connection to read associated objects.
     */
    protected Reference copyInto(Reference copyObj, Connection con) throws TorqueException
    {
        return copyInto(copyObj, true, con);
    }
  
    /**
     * Fills the copyObj with the contents of this object.
     * If deepcopy is true, The associated objects are also copied
     * and treated as new objects.
     *
     * @param copyObj the object to fill.
     * @param deepcopy whether the associated objects should be copied.
     */
    protected Reference copyInto(Reference copyObj, boolean deepcopy) throws TorqueException
    {
        copyObj.setBookId(bookId);
        copyObj.setReaderId(readerId);
        copyObj.setTest(test);

        copyObj.setBookId( 0);
        copyObj.setReaderId( 0);

        if (deepcopy)
        {
        }
        return copyObj;
    }
        
    
    /**
     * Fills the copyObj with the contents of this object using connection.
     * If deepcopy is true, The associated objects are also copied
     * and treated as new objects.
     *
     * @param copyObj the object to fill.
     * @param deepcopy whether the associated objects should be copied.
     * @param con the database connection to read associated objects.
     */
    protected Reference copyInto(Reference copyObj, boolean deepcopy, Connection con) throws TorqueException
    {
        copyObj.setBookId(bookId);
        copyObj.setReaderId(readerId);
        copyObj.setTest(test);

        copyObj.setBookId( 0);
        copyObj.setReaderId( 0);

        if (deepcopy)
        {
        }
        return copyObj;
    }
    
    

    /**
     * returns a peer instance associated with this om.  Since Peer classes
     * are not to have any instance attributes, this method returns the
     * same instance for all member of this class. The method could therefore
     * be static, but this would prevent one from overriding the behavior.
     */
    public ReferencePeer getPeer()
    {
        return peer;
    }

    /**
     * Retrieves the TableMap object related to this Table data without
     * compiler warnings of using getPeer().getTableMap().
     *
     * @return The associated TableMap object.
     */
    public TableMap getTableMap() throws TorqueException
    {
        return ReferencePeer.getTableMap();
    }


    public String toString()
    {
        StringBuffer str = new StringBuffer();
        str.append("Reference:\n");
        str.append("BookId = ")
           .append(getBookId())
           .append("\n");
        str.append("ReaderId = ")
           .append(getReaderId())
           .append("\n");
        str.append("Test = ")
           .append(getTest())
           .append("\n");
        return(str.toString());
    }
}
