package fr.iut2.tc4.projet.torque;

/**
 * Table des cours
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Dec 16 14:29:30 CET 2010]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class CoursPeer
    extends fr.iut2.tc4.projet.torque.BaseCoursPeer
{
    /** Serial version */
    private static final long serialVersionUID = 1292506170763L;

}
