package fr.iut2.tc4.projet.torque;


import org.apache.torque.om.Persistent;

/**
 * Table des notes
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Wed Dec 15 08:50:33 CET 2010]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */
public  class Note
    extends fr.iut2.tc4.projet.torque.BaseNote
    implements Persistent
{
    /** Serial version */
    private static final long serialVersionUID = 1292399433659L;

}
